{
 "title": "springboot Dashboard",
 "description": "springboot metrics",
 "tags": [
  "common",
  "new"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "department",
    "label": "部门",
    "query": "show tag values from process_uptime with key =\"department\" where $timeFilter"
   },
   {
    "name": "group",
    "label": "项目组",
    "query": "show tag values from process_uptime with key =\"group\"  where department ='${department:text}'   AND $timeFilter"
   },
   {
    "name": "project",
    "label": "项目",
    "query": "show tag values from process_uptime with key =\"project\"  where department ='${department:text}'   AND \"group\" ='${group:text}' AND $timeFilter"
   },
   {
    "name": "host",
    "label": "域名",
    "query": "show tag values from process_uptime with key =\"host\" where project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}' AND $timeFilter"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "select ip, value from process_uptime   where host ='${host:text}' and project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}' AND $timeFilter"
   },
   {
    "name": "status",
    "label": "状态码",
    "query": "show tag values from http_server_requests with key =\"status\"  where host ='${host:text}' and project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}'  AND $timeFilter"
   },
   {
    "name": "uri",
    "label": "请求Url",
    "query": "show tag values from http_server_requests with key =\"uri\"  where    host ='${host:text}' and project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}' and status =~ /$status$/   AND $timeFilter"
   },
   {
    "name": "commomdkey",
    "label": "commomdkey",
    "query": "show tag values from hystrix_requests with key =\"key\"  where host ='${host:text}' and project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}'  AND $timeFilter"
   },
   {
    "name": "resource",
    "label": "resource",
    "query": "show tag values from sentinel with key =\"resource\"  where host ='${host:text}' and project='${project:text}'  and department ='${department:text}'   AND \"group\" ='${group:text}'  AND $timeFilter"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "启动时间",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "measurement": "process_start_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "进程CPU使用率",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "占系统总cpu的比例",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "value",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "线程数",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "measurement": "jvm_threads_live",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "年轻代GC次数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "jvm_gc_pause",
     "query": "SELECT sum(\"count\") FROM \"jvm_gc_pause\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"ip\" =~ /^$ip$/ AND \"project\" =~ /^$project$/ AND \"host\" =~ /^$host$/ AND \"action\" = 'end_of_minor_GC' AND \"cause\" != 'CMS_Final_Remark') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" }
     ]
    }
   ]
  },
  {
   "title": "老年代GC次数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "jvm_gc_pause",
     "query": "SELECT sum(\"count\") FROM \"jvm_gc_pause\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"ip\" =~ /^$ip$/ AND \"project\" =~ /^$project$/ AND \"host\" =~ /^$host$/ AND (\"cause\" = 'CMS\\\\ Final\\\\ Remark' OR \"cause\" = 'CMS_Final_Remark' OR action='end_of_major_GC' )) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS_Final_Remark" }
     ]
    }
   ]
  },
  {
   "title": "Heap已使用",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "A",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" }
     ]
    },
    {
     "alias": "B",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" }
     ]
    },
    {
     "alias": "C",
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" }
     ]
    }
   ]
  },
  {
   "title": "运行时长",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "process_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "时间最大误差",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "machine_date_offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 300" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "系统CPU使用率",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "占系统总cpu数比例",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "value",
     "measurement": "system_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "系统最近1分钟负载",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "measurement": "system_load_average_1m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "年轻代GC平均耗时",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "alias": "count",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" }
     ]
    },
    {
     "alias": "time",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" }
     ]
    }
   ]
  },
  {
   "title": "老年代GC平均耗时",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "alias": "time",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS_Final_Remark" }
     ]
    },
    {
     "alias": "count",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS_Final_Remark" }
     ]
    }
   ]
  },
  {
   "title": "Heap最大值",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "A",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" }
     ]
    },
    {
     "alias": "B",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" }
     ]
    },
    {
     "alias": "C",
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" }
     ]
    }
   ]
  },
  {
   "title": "打开文件数",
   "type": "michaeldmoore-annunciator-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "process_files_open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "请求量/服务器IP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" }
     ]
    },
    {
     "alias": "[[tag_ip]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" }
     ]
    },
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http_server_requests",
     "query": "SELECT sum(\"count\")/60 FROM \"http_server_requests\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"host\" =~ /^$host$/ AND \"status\" =~ /^$status$/) AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" }
     ]
    }
   ]
  },
  {
   "title": "请求量/状态码",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" }
     ]
    },
    {
     "alias": "[[tag_status]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" }
     ]
    }
   ]
  },
  {
   "title": "请求量/请求Url",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$uri$/" }
     ]
    },
    {
     "alias": "[[tag_uri]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$uri$/" }
     ]
    }
   ]
  },
  { "title": "Request Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "耗时/请求Url",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_uri]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "uri", "operator": "=~", "value": "/^$uri$/" }
     ]
    }
   ]
  },
  {
   "title": "慢请求（10s平均值）",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "measurement": "http_server_requests",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ],
      [
       { "params": [ "uri" ], "type": "field" },
       { "params": [ "请求Url" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "状态值" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "top" },
       { "params": [ "平均耗时" ], "type": "alias" }
      ],
      [
       { "params": [ "99_percentile" ], "type": "field" },
       { "params": [ "耗时TP99" ], "type": "alias" }
      ],
      [
       { "params": [ "upper" ], "type": "field" },
       { "params": [ "最大值" ], "type": "alias" }
      ],
      [
       { "params": [ "lower" ], "type": "field" },
       { "params": [ "最小值" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "请求量" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "status", "operator": "=~", "value": "/^$status$/" },
      { "condition": "AND", "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "守护线程数",
       "measurement": "jvm_threads_daemon",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "线程数",
       "measurement": "jvm_threads_live",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "线程数峰值",
       "measurement": "jvm_threads_peak",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "measurement": "system_load_average_1m",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "measurement": "process_cpu_usage",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "measurement": "system_cpu_usage",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "Process Files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "open",
       "measurement": "process_files_open",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "max",
       "measurement": "process_files_max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "系统时间误差",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "误差值",
       "measurement": "machine_date_offset",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "JVM GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "年轻代GC次数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "jvm_gc_pause",
     "query": "SELECT sum(\"count\") FROM \"jvm_gc_pause\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"ip\" =~ /^$ip$/ AND \"project\" =~ /^$project$/ AND \"host\" =~ /^$host$/ AND \"cause\" != 'CMS_Final_Remark' AND \"action\" = 'end_of_minor_GC') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" }
     ]
    }
   ]
  },
  {
   "title": "年轻代GC平均耗时",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "alias": "count",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" }
     ]
    },
    {
     "alias": "time",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "end_of_minor_GC" },
      { "condition": "AND", "key": "cause", "operator": "!=", "value": "CMS_Final_Remark" }
     ]
    }
   ]
  },
  {
   "title": "老年代GC次数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "jvm_gc_pause",
     "query": "SELECT sum(\"count\") FROM \"jvm_gc_pause\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"ip\" =~ /^$ip$/ AND \"project\" =~ /^$project$/ AND \"host\" =~ /^$host$/ AND (\"cause\" = 'CMS\\\\ Final\\\\ Remark' OR \"cause\" = 'CMS_Final_Remark' OR action='end_of_major_GC' )) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS\\ Final\\ Remark" }
     ]
    }
   ]
  },
  {
   "title": "老年代GC平均耗时",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "alias": "time",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS\\ Final\\ Remark" }
     ]
    },
    {
     "alias": "count",
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "cause", "operator": "=", "value": "CMS\\ Final\\ Remark" }
     ]
    }
   ]
  },
  {
   "title": "allocated/promoted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "jvm_gc_memory_allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "measurement": "jvm_gc_memory_promoted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]]([[tag_cause]])",
     "groupBy": [
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" }
     ],
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_action]]([[tag_cause]])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" }
     ],
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "GC明细",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "measurement": "jvm_gc_pause",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ],
      [
       { "params": [ "action" ], "type": "field" }
      ],
      [
       { "params": [ "cause" ], "type": "field" }
      ],
      [
       { "params": [ "count" ], "type": "field" }
      ],
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Heap Used",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "NonHeap Used",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "NonHeap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  },
  { "title": "JVM Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Eden_Space" }
     ]
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "Par_Survivor_Space" }
     ]
    }
   ]
  },
  {
   "title": "CMS Old Gen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" }
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "area" ], "type": "tag" },
      { "params": [ "statistic" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
      { "condition": "AND", "key": "id", "operator": "=", "value": "CMS_Old_Gen" }
     ]
    }
   ]
  },
  {
   "title": "JVM NonHeap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Cache",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Code_Cache" }
       ]
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed_Class_Space" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed_Class_Space" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Compressed\\ Class\\ Space" }
       ]
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" }
       ]
      },
      {
       "alias": "committed",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "id" ], "type": "tag" },
        { "params": [ "area" ], "type": "tag" },
        { "params": [ "statistic" ], "type": "tag" }
       ],
       "measurement": "jvm_memory_max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "Metaspace" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "direct buffer size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "measurement": "jvm_buffer_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
       ]
      },
      {
       "measurement": "jvm_buffer_total_capacity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
       ]
      }
     ]
    },
    {
     "title": "direct buffer count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "jvm_buffer_count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "spread"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "direct" }
       ]
      }
     ]
    },
    {
     "title": "mapped buffer size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "measurement": "jvm_buffer_memory_used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
       ]
      },
      {
       "measurement": "jvm_buffer_total_capacity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
       ]
      }
     ]
    },
    {
     "title": "mapped buffer count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" }
       ],
       "measurement": "jvm_buffer_count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "spread"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "id", "operator": "=", "value": "mapped" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Tomcat线程数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "当前值",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "tomcat_threads_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "alias": "busy数量",
     "measurement": "tomcat_threads_busy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "alias": "最大值",
     "measurement": "tomcat_threads_config_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "接收/发送数据",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "接收数量",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "tomcat_global_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "alias": "发送数量",
     "measurement": "tomcat_global_sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "请求数",
     "measurement": "tomcat_global_request",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "alias": "错误请求数",
     "measurement": "tomcat_global_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "alias": "servlet错误数",
     "measurement": "tomcat_servlet_error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "Datasource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datasource Common",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_source]]_connectMax",
       "groupBy": [
        { "params": [ "source" ], "type": "tag" }
       ],
       "measurement": "datasource",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "connectMax" }
       ]
      },
      {
       "alias": "[[tag_source]]_connectMin",
       "groupBy": [
        { "params": [ "source" ], "type": "tag" }
       ],
       "measurement": "datasource",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "connectMin" }
       ]
      },
      {
       "alias": "[[tag_source]]_connectActive",
       "groupBy": [
        { "params": [ "source" ], "type": "tag" }
       ],
       "measurement": "datasource",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "connectActive" }
       ]
      }
     ]
    },
    {
     "title": "Datasource Customized",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_source]]_[[tag_type]]",
       "groupBy": [
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "measurement": "datasource",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "connectMax" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "connectCount" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "connectMin" },
        { "condition": "AND", "key": "type", "operator": "!=", "value": "notEmptyWaitNanos" }
       ]
      }
     ]
    },
    {
     "title": "DataSource Detail",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "measurement": "datasource",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Hystrix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "错误数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_key]]_错误数",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_errors",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "[[tag_key]]_执行数",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_execution",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "[[tag_key]]_请求数",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_requests",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "[[tag_key]]_Fallback请求数",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_fallback",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "熔断状态",
     "type": "blackmirror1-singlestat-math-panel",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "measurement": "hystrix_circuit_breaker_open",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "key", "operator": "=~", "value": "/^$commomdkey$/" }
       ]
      }
     ]
    },
    {
     "title": "延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_key]]_执行延迟",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_latency_execution",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "[[tag_key]]_总延迟",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_latency_total",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      }
     ]
    },
    {
     "title": "线程数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_key]]_current",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_threadpool_concurrent_execution_current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "alias": "[[tag_key]]_max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "hystrix_threadpool_concurrent_execution_rolling_max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "JVM ClassesLoad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "classesload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    },
    {
     "measurement": "jvm_classes_unloaded",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "department", "operator": "=~", "value": "/^$department$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" }
     ]
    }
   ]
  },
  {
   "title": "sentinel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "统计数量",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]_[[tag_type]]",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "measurement": "sentinel",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "resource", "operator": "=~", "value": "/^$resource$/" }
       ]
      },
      {
       "alias": "[[tag_resource]]_success",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "measurement": "sentinel_rt",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "resource", "operator": "=~", "value": "/^$resource$/" }
       ]
      }
     ]
    },
    {
     "title": "响应时间",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]_rt",
       "groupBy": [
        { "params": [ "resource" ], "type": "tag" },
        { "params": [ "type" ], "type": "tag" }
       ],
       "measurement": "sentinel_rt",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$ip$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "resource", "operator": "=~", "value": "/^$resource$/" }
       ]
      }
     ]
    },
    {
     "title": "异常数量_应用维度（不包含设置忽略的异常）",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" }
       ],
       "measurement": "sentinel",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "exception" }
       ]
      }
     ]
    },
    {
     "title": "异常数量_实例维度（不包含设置忽略的异常）",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]_[[tag_ip]]",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "sentinel",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "exception" }
       ]
      }
     ]
    },
    {
     "title": "降级数量_应用维度",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]_[[tag_type]]",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" }
       ],
       "measurement": "sentinel",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "block" }
       ]
      }
     ]
    },
    {
     "title": "降级数量_实例维度",
     "type": "graph",
     "description": "Pass：进入资源的请求数\n\nBlock：降级的资源\n\nSuccess：进入资源内部执行完成的数量，执行异常回调包含在内\n\nException：进入异常回调数量，不包含设置忽略的异常\n\nRt：进入资源运行耗时（包含异常回调时间）",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_resource]]_[[tag_ip]]",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "resource" ], "type": "tag" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "sentinel",
       "query": "SELECT sum(\"value\") FROM \"sentinel\" WHERE (\"department\" =~ /^$department$/ AND \"group\" =~ /^$group$/ AND \"project\" =~ /^$project$/ AND \"ip\" =~ /^$ip$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"resource\", \"type\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "department", "operator": "=~", "value": "/^$department$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "block" }
       ]
      }
     ]
    }
   ]
  }
 ]
}